# Generated by Django 3.1.4 on 2021-01-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_bgm_on',
            field=models.BooleanField(default=True),
        ),
    ]
