# Generated by Django 3.1.4 on 2021-02-20 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(max_length=200)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
                ('user_reported', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
