# Generated by Django 3.1.4 on 2021-02-20 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0005_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ManyToManyField(related_name='reporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='report',
            name='user_reported',
        ),
        migrations.AddField(
            model_name='report',
            name='user_reported',
            field=models.ManyToManyField(related_name='user_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
